<h3>Mes compétences en développement Back-end</h3>

<div>Méthodologie :</div>
<ul>
	<li>
		Respect des conventions de programmation :
		<ul>
			<li>Respect des conventions de programmation PSR</li>
			<li>Indentation du code, pour simplifier la lecture</li>
			<li>Respect des normes PhpDoc et commentaire du code pour simplifier la compréhension</li>
		</ul>
	</li>
	<li>
		Création et développement dans une strucutre MVC / PDO
		<ul>
			<li>Création et maintien d’un framework maison dédié aux extranets et sites Web (kateji)</li>
			<li>Compréhension et adaptation à l'utilisation et fonctionnement des frameworks</li>
		</ul>
	</li>
</ul>

<div>Langages :</div>
<ul>
	<li>
		<i>Programmation :</i> PHP (Programmation Orientée Objet), API ...
	</li>
	<li>
		<i>Base de données :</i> Mysql, PostgreSQL, MariaDB
	</li>
	<li>
		<i>Templating :</i> Smarty, Twig, Moustache
	</li>
	<li>
		<i>Autres :</i> Htaccess, XML, JSON
	</li>
</ul>

