<section id='content-accueil'>
	<h1>THOMAS JACQUEY</h1>
	
	<h2>LEAD DEVELOPPEUR PHP</h2>
	
	<h3>Spécialisé : Extranet / Intranet / Application spécifique / Web </h3>
	
	<hr/>
	
	<p>
		Conquérir le web est une chose
		<br/>
		Conquérir l'internaute en est une autre
	</p>
</section>

<section class='pdf icon-article-alt'>
    <a href='{{infosEnv.SCRIPT_NAME}}{{linkData.linkPdfCV}}'>
        Télécharger mon CV au format PDF
    </a>
</section>

